import { Comercio } from '@/types/comercio';

export const MOCK_COMERCIOS: Comercio[] = [
  // ==========================================
  // 10 COMERCIOS EN GRAND BOURG (MALVINAS ARGENTINAS)
  // 2 Gold, 4 Premium, 4 Standar
  // ==========================================

  // 1. [GOLD 1 - Grand Bourg] Parrilla & Carnicería Los Troncos
  {
    id: 'gb-gold-01',
    nombre: 'Parrilla & Carnicería Los Troncos',
    rubro: 'Carnicería',
    direccion: 'Av. El Callao 1120, Grand Bourg',
    telefono: '+54 11 4660-1234',
    whatsapp: '+5491146601234',
    esta_abierto: true,
    latitud: -34.4851,
    longitud: -58.7155,
    descripcion: 'Cortes seleccionados de ternera de pastura, achuras frescas y leña de quebracho colorado. Atendido por sus dueños desde 1998.',
    horario: 'Lunes a Sábados de 8:00 a 20:30 | Domingos de 8:30 a 13:30',
    tiene_catalogo: true,
    nivel: 'gold',
    nivel_solicitado: 'gold',
    fecha_inicio_nivel: '2026-09-01T12:00:00.000Z',
    fecha_vencimiento_nivel: '2026-10-01T12:00:00.000Z',
    tipo_atencion: 'ambos',
    radio_entrega_metros: 3000,
    zona_envio_descripcion: 'Grand Bourg centro, Tierras Altas e Ing. Adolfo Sourdeaux.',
    productos: [
      {
        id: 'p-gb-g1-1',
        comercio_id: 'gb-gold-01',
        nombre: 'Asado de Tira Especial (1 kg)',
        descripcion: 'Corte parrillero tierno y con poca grasa, calidad premium garantizada.',
        precio: 9800,
        precio_oferta: 7990,
        es_oferta: true,
        descuento_porcentaje: 18,
        imagen_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
        categoria: 'Carnes Vacunas',
      },
      {
        id: 'p-gb-g1-2',
        comercio_id: 'gb-gold-01',
        nombre: 'Vacio de Novillo Seleccionado (1 kg)',
        descripcion: 'Ideal para la parrilla o al horno con papas rústicas.',
        precio: 10500,
        precio_oferta: 8900,
        es_oferta: true,
        descuento_porcentaje: 15,
        imagen_url: 'https://images.unsplash.com/photo-1558030006-450675393462?w=600&auto=format&fit=crop&q=80',
        categoria: 'Carnes Vacunas',
      },
      {
        id: 'p-gb-g1-3',
        comercio_id: 'gb-gold-01',
        nombre: 'Chorizo Bombón Casero (1 kg)',
        descripcion: 'Puro cerdo especiado con receta criolla sin conservantes artificiales.',
        precio: 6500,
        precio_oferta: 5200,
        es_oferta: true,
        descuento_porcentaje: 20,
        imagen_url: 'https://images.unsplash.com/photo-1597362925123-77861d3fbac7?w=600&auto=format&fit=crop&q=80',
        categoria: 'Embutidos',
      },
      {
        id: 'p-gb-g1-4',
        comercio_id: 'gb-gold-01',
        nombre: 'Matambre de Cerdo Tierno (1 kg)',
        descripcion: 'Excelente para tiernizar a la pizza o al limón a la parrilla.',
        precio: 9200,
        precio_oferta: 7800,
        es_oferta: true,
        descuento_porcentaje: 15,
        imagen_url: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=600&auto=format&fit=crop&q=80',
        categoria: 'Cortes de Cerdo',
      },
      {
        id: 'p-gb-g1-5',
        comercio_id: 'gb-gold-01',
        nombre: 'Bolsa de Carbón Vegetal de Quebracho (4 kg)',
        descripcion: 'Brasas duraderas de alto poder calórico.',
        precio: 3500,
        precio_oferta: 2800,
        es_oferta: true,
        descuento_porcentaje: 20,
        imagen_url: 'https://images.unsplash.com/photo-1527661591475-527312dd65f5?w=600&auto=format&fit=crop&q=80',
        categoria: 'Parrilla y Carbón',
      },
    ],
  },

  // 2. [GOLD 2 - Grand Bourg] Farmacia Grand Bourg Centro (DE TURNO 24HS)
  {
    id: 'gb-gold-02',
    nombre: 'Farmacia Grand Bourg Centro',
    rubro: 'Farmacia',
    direccion: 'Av. Eva Perón 1450, Grand Bourg',
    telefono: '+54 11 4660-5678',
    whatsapp: '+5491146605678',
    esta_abierto: true,
    esta_de_turno: true,
    fecha_turno: '2026-09-22',
    latitud: -34.4838,
    longitud: -58.7172,
    descripcion: 'Atención farmacéutica profesional las 24 horas. Amplio stock en medicación de urgencia, obras sociales y perfumería.',
    horario: 'De Turno 24 Horas Continuas',
    tiene_catalogo: true,
    nivel: 'gold',
    nivel_solicitado: 'gold',
    fecha_inicio_nivel: '2026-09-10T10:00:00.000Z',
    fecha_vencimiento_nivel: '2026-10-10T10:00:00.000Z',
    tipo_atencion: 'ambos',
    radio_entrega_metros: 2500,
    zona_envio_descripcion: 'Envíos nocturnos y diurnos en todo Grand Bourg.',
    productos: [
      {
        id: 'p-gb-g2-1',
        comercio_id: 'gb-gold-02',
        nombre: 'Termómetro Digital Rápido Preciso',
        descripcion: 'Medición precisa en 60 segundos con señal sonora y memoria de última medición.',
        precio: 8900,
        precio_oferta: 6990,
        es_oferta: true,
        descuento_porcentaje: 21,
        imagen_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
        categoria: 'Salud y Botiquín',
      },
      {
        id: 'p-gb-g2-2',
        comercio_id: 'gb-gold-02',
        nombre: 'Alcohol en Gel Sanitizante 70% (500 ml)',
        descripcion: 'Fórmula hidratante con glicerina, no reseca la piel.',
        precio: 3600,
        precio_oferta: 2700,
        es_oferta: true,
        descuento_porcentaje: 25,
        imagen_url: 'https://images.unsplash.com/photo-1584744982491-665216d95f8b?w=600&auto=format&fit=crop&q=80',
        categoria: 'Higiene',
      },
      {
        id: 'p-gb-g2-3',
        comercio_id: 'gb-gold-02',
        nombre: 'Protector Solar Dermaglós FPS 50 (250 ml)',
        descripcion: 'Protección alta UVA/UVB resistente al agua e hipoalergénico.',
        precio: 16500,
        precio_oferta: 13200,
        es_oferta: true,
        descuento_porcentaje: 20,
        imagen_url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80',
        categoria: 'Cuidado de la Piel',
      },
      {
        id: 'p-gb-g2-4',
        comercio_id: 'gb-gold-02',
        nombre: 'Pañales Pampers Premium Care Grande (G x 54)',
        descripcion: 'Máxima suavidad y absorción para mantener al bebé seco hasta 12 horas.',
        precio: 22000,
        precio_oferta: 18500,
        es_oferta: true,
        descuento_porcentaje: 16,
        imagen_url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&auto=format&fit=crop&q=80',
        categoria: 'Bebés y Maternidad',
      },
    ],
  },

  // 3. [PREMIUM 1 - Grand Bourg] Pizzería & Empanadas La Farola (HORARIO CORTADO)
  {
    id: 'gb-prem-01',
    nombre: 'Pizzería & Empanadas La Farola',
    rubro: 'Gastronomía',
    direccion: 'Calle Francisco Seguí 1520, Grand Bourg',
    telefono: '+54 11 4660-3322',
    whatsapp: '+5491146603322',
    esta_abierto: true,
    tiene_horario_cortado: true,
    horario_manana: '11:30 - 14:30',
    horario_tarde: '19:30 - 23:30',
    latitud: -34.4862,
    longitud: -58.7140,
    descripcion: 'Pizzas a la piedra al horno de barro y empanadas salteñas de carne cortada a cuchillo.',
    tiene_catalogo: true,
    nivel: 'premium',
    nivel_solicitado: 'premium',
    fecha_inicio_nivel: '2026-09-05T12:00:00.000Z',
    fecha_vencimiento_nivel: '2026-10-05T12:00:00.000Z',
    tipo_atencion: 'ambos',
    radio_entrega_metros: 3500,
    zona_envio_descripcion: 'Todo Grand Bourg y límites con Polvorines.',
    productos: [
      {
        id: 'p-gb-p1-1',
        comercio_id: 'gb-prem-01',
        nombre: 'Pizza Grande Muzzarella Especial + Fainá',
        descripcion: 'Salsa casera de tomates seleccionados, abundante muzzarella y aceitunas negras.',
        precio: 11000,
        precio_oferta: 8900,
        es_oferta: true,
        descuento_porcentaje: 19,
        imagen_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
        categoria: 'Pizzas',
      },
      {
        id: 'p-gb-p1-2',
        comercio_id: 'gb-prem-01',
        nombre: 'Docena de Empanadas Criollas al Horno de Barro',
        descripcion: 'Carne cortada a cuchillo, jamón y queso, humita o pollo suave.',
        precio: 14400,
        precio_oferta: 11900,
        es_oferta: true,
        descuento_porcentaje: 17,
        imagen_url: 'https://images.unsplash.com/photo-1628294895950-9805252327bc?w=600&auto=format&fit=crop&q=80',
        categoria: 'Empanadas',
      },
    ],
  },

  // 4. [PREMIUM 2 - Grand Bourg] Panadería San Martín
  {
    id: 'gb-prem-02',
    nombre: 'Panadería San Martín',
    rubro: 'Panadería',
    direccion: 'Av. San Martín 840, Grand Bourg',
    telefono: '+54 11 4660-8899',
    whatsapp: '+5491146608899',
    esta_abierto: true,
    latitud: -34.4829,
    longitud: -58.7195,
    descripcion: 'Facturas de manteca, chipá correntino recién horneado y masas secas para eventos.',
    horario: 'Lunes a Sábados de 6:30 a 20:30',
    tiene_catalogo: true,
    nivel: 'premium',
    nivel_solicitado: 'premium',
    fecha_inicio_nivel: '2026-09-12T09:00:00.000Z',
    fecha_vencimiento_nivel: '2026-10-12T09:00:00.000Z',
    tipo_atencion: 'local_fisico',
    productos: [
      {
        id: 'p-gb-p2-1',
        comercio_id: 'gb-prem-02',
        nombre: 'Docena de Medialunas de Manteca Calentitas',
        descripcion: 'Clásicas hojaldradas con almíbar aromático.',
        precio: 8200,
        precio_oferta: 6700,
        es_oferta: true,
        descuento_porcentaje: 18,
        imagen_url: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&auto=format&fit=crop&q=80',
        categoria: 'Facturas',
      },
      {
        id: 'p-gb-p2-2',
        comercio_id: 'gb-prem-02',
        nombre: 'Chipá Casero de Queso Criollo (1/2 kg)',
        descripcion: 'Elaborado con harina de mandioca y doble porción de queso marplatense.',
        precio: 5800,
        precio_oferta: 4600,
        es_oferta: true,
        descuento_porcentaje: 20,
        imagen_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
        categoria: 'Especialidades',
      },
    ],
  },

  // 5. [PREMIUM 3 - Grand Bourg] Verdulería & Frutería El Oasis (HORARIO CORTADO)
  {
    id: 'gb-prem-03',
    nombre: 'Verdulería & Frutería El Oasis',
    rubro: 'Verdulería',
    direccion: 'Calle Hipólito Yrigoyen 1980, Grand Bourg',
    telefono: '+54 11 4660-7711',
    whatsapp: '+5491146607711',
    esta_abierto: true,
    tiene_horario_cortado: true,
    horario_manana: '08:30 - 13:00',
    horario_tarde: '16:30 - 20:30',
    latitud: -34.4875,
    longitud: -58.7160,
    descripcion: 'Frutas y verduras frescas del Mercado Central todas las mañanas. Frutos secos y legumbres sueltas.',
    tiene_catalogo: true,
    nivel: 'premium',
    nivel_solicitado: 'premium',
    fecha_inicio_nivel: '2026-09-15T08:00:00.000Z',
    fecha_vencimiento_nivel: '2026-10-15T08:00:00.000Z',
    tipo_atencion: 'ambos',
    radio_entrega_metros: 2000,
    zona_envio_descripcion: 'Reparto barrial en bici y moto sin cargo desde $10.000.',
    productos: [
      {
        id: 'p-gb-p3-1',
        comercio_id: 'gb-prem-03',
        nombre: 'Cajón Familiar de Verduras de Estación (8 kg)',
        descripcion: 'Papas, cebollas, zanahorias, tomates redondos, acelga y zapallitos.',
        precio: 13500,
        precio_oferta: 10900,
        es_oferta: true,
        descuento_porcentaje: 19,
        imagen_url: 'https://images.unsplash.com/photo-1610832958506-aa56368176cf?w=600&auto=format&fit=crop&q=80',
        categoria: 'Combos de Verdulería',
      },
      {
        id: 'p-gb-p3-2',
        comercio_id: 'gb-prem-03',
        nombre: 'Bolsa de Naranjas de Ombligo Dulces (3 kg)',
        descripcion: 'Ideales para exprimir, jugosas y sin semillas.',
        precio: 4800,
        precio_oferta: 3800,
        es_oferta: true,
        descuento_porcentaje: 20,
        imagen_url: 'https://images.unsplash.com/photo-1557800636-894a64c1696f?w=600&auto=format&fit=crop&q=80',
        categoria: 'Frutas',
      },
    ],
  },

  // 6. [PREMIUM 4 - Grand Bourg] Librería & Papelería Arcoíris (CERRADO MOMENTÁNEO)
  {
    id: 'gb-prem-04',
    nombre: 'Librería & Papelería Arcoíris',
    rubro: 'Librería',
    direccion: 'Calle Beiró 410, Grand Bourg',
    telefono: '+54 11 4660-4455',
    whatsapp: '+5491146604455',
    esta_abierto: false,
    cerrado_momentaneo: true,
    motivo_cierre_momentaneo: 'Corte imprevisto de suministro eléctrico en la cuadra. Reabrimos en cuanto regrese la luz.',
    latitud: -34.4849,
    longitud: -58.7210,
    descripcion: 'Artículos escolares, universitarios, fotocopias láser color, anillados e insumos de oficina.',
    horario: 'Lunes a Viernes de 8:30 a 19:30 | Sábados de 9:00 a 13:00',
    tiene_catalogo: true,
    nivel: 'premium',
    nivel_solicitado: 'premium',
    fecha_inicio_nivel: '2026-09-02T11:00:00.000Z',
    fecha_vencimiento_nivel: '2026-10-02T11:00:00.000Z',
    tipo_atencion: 'local_fisico',
    productos: [
      {
        id: 'p-gb-p4-1',
        comercio_id: 'gb-prem-04',
        nombre: 'Set de Dibujo Técnico y Escolar Completo',
        descripcion: 'Regla de 30 cm, escuadras, transportador y microfibras de precisión.',
        precio: 12500,
        precio_oferta: 9900,
        es_oferta: true,
        descuento_porcentaje: 20,
        imagen_url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80',
        categoria: 'Escolar',
      },
      {
        id: 'p-gb-p4-2',
        comercio_id: 'gb-prem-04',
        nombre: 'Cuaderno Universitario Tapa Dura (100 hojas rayadas)',
        descripcion: 'Papel obra de 75g de alta blancura, espiralado reforzado.',
        precio: 5200,
        precio_oferta: 4200,
        es_oferta: true,
        descuento_porcentaje: 19,
        imagen_url: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
        categoria: 'Cuadernos',
      },
    ],
  },

  // 7. [STANDAR 1 - Grand Bourg] Almacén & Fiambrería Don Raúl
  {
    id: 'gb-std-01',
    nombre: 'Almacén & Fiambrería Don Raúl',
    rubro: 'Almacén',
    direccion: 'Calle Batalla de Chacabuco 730, Grand Bourg',
    telefono: '+54 11 4660-6644',
    whatsapp: '+5491146606644',
    esta_abierto: true,
    latitud: -34.4882,
    longitud: -58.7180,
    descripcion: 'Fiambres de primera marca al corte, quesos de campo, bebidas frías y almacén general de barrio.',
    horario: 'Lunes a Sábados de 8:30 a 13:00 y de 16:30 a 20:30',
    tiene_catalogo: true,
    nivel: 'standar',
    nivel_solicitado: 'standar',
    tipo_atencion: 'local_fisico',
    productos: [
      {
        id: 'p-gb-s1-1',
        comercio_id: 'gb-std-01',
        nombre: 'Jamón Cocido Natural Feteado (250 g)',
        descripcion: 'Calidad superior, tierno y con bajo contenido en sodio.',
        precio: 3600,
        es_oferta: false,
        categoria: 'Fiambrería',
      },
      {
        id: 'p-gb-s1-2',
        comercio_id: 'gb-std-01',
        nombre: 'Queso Cremoso La Paulina (1 kg)',
        descripcion: 'Ideal para derretir en pizzas, tartas y empanadas.',
        precio: 8200,
        es_oferta: false,
        categoria: 'Lácteos y Quesos',
      },
    ],
  },

  // 8. [STANDAR 2 - Grand Bourg] Ferretería Industrial El Tornillo (HORARIO CORTADO)
  {
    id: 'gb-std-02',
    nombre: 'Ferretería Industrial El Tornillo',
    rubro: 'Ferretería',
    direccion: 'Calle Coronel Bogado 1240, Grand Bourg',
    telefono: '+54 11 4660-9933',
    whatsapp: '+5491146609933',
    esta_abierto: true,
    tiene_horario_cortado: true,
    horario_manana: '08:00 - 12:30',
    horario_tarde: '15:00 - 19:30',
    latitud: -34.4815,
    longitud: -58.7135,
    descripcion: 'Herramientas eléctricas y manuales, bulonería de precisión, pinturas y sanitarios para el hogar.',
    tiene_catalogo: true,
    nivel: 'standar',
    nivel_solicitado: 'standar',
    tipo_atencion: 'local_fisico',
    productos: [
      {
        id: 'p-gb-s2-1',
        comercio_id: 'gb-std-02',
        nombre: 'Cinta Métrica Profesional 5 Metros',
        descripcion: 'Carcasa de goma resistente a caídas con traba antideslizante.',
        precio: 4500,
        es_oferta: false,
        categoria: 'Herramientas',
      },
    ],
  },

  // 9. [STANDAR 3 - Grand Bourg] Pet Shop & Veterinaria Huellitas
  {
    id: 'gb-std-03',
    nombre: 'Pet Shop & Veterinaria Huellitas',
    rubro: 'Veterinaria',
    direccion: 'Calle Guayaquil 920, Grand Bourg',
    telefono: '+54 11 4660-2211',
    whatsapp: '+5491146602211',
    esta_abierto: true,
    latitud: -34.4890,
    longitud: -58.7125,
    descripcion: 'Alimentos balanceados por bolsa y sueltos, antipulgas, collares, correas y atención clínica veterinaria.',
    horario: 'Lunes a Viernes de 9:00 a 19:00 | Sábados de 9:00 a 14:00',
    tiene_catalogo: true,
    nivel: 'standar',
    nivel_solicitado: 'standar',
    tipo_atencion: 'ambos',
    radio_entrega_metros: 2500,
    zona_envio_descripcion: 'Envíos de bolsas grandes de alimento balanceado a domicilio.',
    productos: [
      {
        id: 'p-gb-s3-1',
        comercio_id: 'gb-std-03',
        nombre: 'Alimento Perro Adulto Raza Mediana/Grande (15 kg)',
        descripcion: 'Nutrición balanceada con proteína de pollo y arroz.',
        precio: 29500,
        es_oferta: false,
        categoria: 'Alimentos para Mascotas',
      },
    ],
  },

  // 10. [STANDAR 4 - Grand Bourg] Kiosco & Polirrubro 24hs La Estación
  {
    id: 'gb-std-04',
    nombre: 'Kiosco & Polirrubro 24hs La Estación',
    rubro: 'Kiosco',
    direccion: 'Av. Eva Perón 980 (frente a Estación Grand Bourg), Grand Bourg',
    telefono: '+54 11 4660-7788',
    whatsapp: '+5491146607788',
    esta_abierto: true,
    latitud: -34.4840,
    longitud: -58.7168,
    descripcion: 'Golosinas, cigarrillos, recargas de tarjeta SUBE, bebidas bien heladas y snacks al paso.',
    horario: 'Abierto 24 Horas los 365 días del año',
    tiene_catalogo: true,
    nivel: 'standar',
    nivel_solicitado: 'standar',
    tipo_atencion: 'local_fisico',
    productos: [
      {
        id: 'p-gb-s4-1',
        comercio_id: 'gb-std-04',
        nombre: 'Alfajor Triple de Chocolate con Dulce de Leche',
        descripcion: 'Clásico alfajor con baño de repostería artesanal.',
        precio: 1400,
        es_oferta: false,
        categoria: 'Golosinas',
      },
    ],
  },

  // ==========================================
  // 10 COMERCIOS EN MAQUINISTA SAVIO (ESCOBAR)
  // 2 Gold, 4 Premium, 4 Standar
  // ==========================================

  // 11. [GOLD 1 - Maquinista Savio] Supermercado y Carnicería Savio Norte
  {
    id: 'ms-gold-01',
    nombre: 'Supermercado y Carnicería Savio Norte',
    rubro: 'Almacén',
    direccion: 'Ruta Provincial 26 N° 2450, Maquinista Savio',
    telefono: '+54 11 4880-1122',
    whatsapp: '+5491148801122',
    esta_abierto: true,
    latitud: -34.4350,
    longitud: -58.7850,
    descripcion: 'Pioneros en Maquinista Savio. Carnicería propia de primera calidad, fiambrería, panadería y bazar con precios mayoristas y minoristas.',
    horario: 'Lunes a Sábados de 8:00 a 21:00 | Domingos de 8:30 a 14:00',
    tiene_catalogo: true,
    nivel: 'gold',
    nivel_solicitado: 'gold',
    fecha_inicio_nivel: '2026-09-08T10:00:00.000Z',
    fecha_vencimiento_nivel: '2026-10-08T10:00:00.000Z',
    tipo_atencion: 'ambos',
    radio_entrega_metros: 4000,
    zona_envio_descripcion: 'Todo Savio, Garín este y límites con Pilar.',
    productos: [
      {
        id: 'p-ms-g1-1',
        comercio_id: 'ms-gold-01',
        nombre: 'Bife de Chorizo de Novillito Especial (1 kg)',
        descripcion: 'Tierno, jugoso y con corte parejo para sartén o brasas.',
        precio: 11500,
        precio_oferta: 9300,
        es_oferta: true,
        descuento_porcentaje: 19,
        imagen_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
        categoria: 'Carnicería',
      },
      {
        id: 'p-ms-g1-2',
        comercio_id: 'ms-gold-01',
        nombre: 'Aceite de Girasol Puro Cocinero (1.5 Litros)',
        descripcion: 'Calidad tradicional para cocinar y freír.',
        precio: 3400,
        precio_oferta: 2750,
        es_oferta: true,
        descuento_porcentaje: 19,
        imagen_url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
        categoria: 'Almacén',
      },
      {
        id: 'p-ms-g1-3',
        comercio_id: 'ms-gold-01',
        nombre: 'Yerba Mate Playadito con Palo (1 kg)',
        descripcion: 'Sabor suave y duradero, la favorita de los mates barriales.',
        precio: 4900,
        precio_oferta: 3950,
        es_oferta: true,
        descuento_porcentaje: 19,
        imagen_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&auto=format&fit=crop&q=80',
        categoria: 'Almacén',
      },
      {
        id: 'p-ms-g1-4',
        comercio_id: 'ms-gold-01',
        nombre: 'Pack Leche Entera Larga Vida La Serenísima (6 x 1L)',
        descripcion: 'Fortificada con vitaminas A, C y D.',
        precio: 8900,
        precio_oferta: 7200,
        es_oferta: true,
        descuento_porcentaje: 19,
        imagen_url: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
        categoria: 'Lácteos',
      },
      {
        id: 'p-ms-g1-5',
        comercio_id: 'ms-gold-01',
        nombre: 'Jabón Líquido para Ropa Ala Ecolavado (3 Litros)',
        descripcion: 'Remoción profunda de manchas en ciclos cortos.',
        precio: 9800,
        precio_oferta: 7900,
        es_oferta: true,
        descuento_porcentaje: 19,
        imagen_url: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=600&auto=format&fit=crop&q=80',
        categoria: 'Limpieza',
      },
    ],
  },

  // 12. [GOLD 2 - Maquinista Savio] Farmacia Savio Express (DE TURNO 24HS)
  {
    id: 'ms-gold-02',
    nombre: 'Farmacia Savio Express',
    rubro: 'Farmacia',
    direccion: 'Calle Juan XXIII 1120, Maquinista Savio',
    telefono: '+54 11 4880-4433',
    whatsapp: '+5491148804433',
    esta_abierto: true,
    esta_de_turno: true,
    fecha_turno: '2026-09-22',
    latitud: -34.4365,
    longitud: -58.7880,
    descripcion: 'Farmacia de turno las 24 horas en Maquinista Savio. Descuentos con PAMI, IOMA y prepagas. Envío de medicación a domicilio.',
    horario: 'Abierto 24 Horas de Turno Activo',
    tiene_catalogo: true,
    nivel: 'gold',
    nivel_solicitado: 'gold',
    fecha_inicio_nivel: '2026-09-03T11:00:00.000Z',
    fecha_vencimiento_nivel: '2026-10-03T11:00:00.000Z',
    tipo_atencion: 'ambos',
    radio_entrega_metros: 3500,
    zona_envio_descripcion: 'Entregas a domicilio en Maquinista Savio y barrios aledaños.',
    productos: [
      {
        id: 'p-ms-g2-1',
        comercio_id: 'ms-gold-02',
        nombre: 'Tensiómetro Digital de Brazo Automático',
        descripcion: 'Detector de arritmias, pantalla grande iluminada y 60 memorias.',
        precio: 36000,
        precio_oferta: 28900,
        es_oferta: true,
        descuento_porcentaje: 20,
        imagen_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80',
        categoria: 'Salud y Diagnóstico',
      },
      {
        id: 'p-gb-g2-2',
        comercio_id: 'ms-gold-02',
        nombre: 'Pack Toallitas Húmedas para Bebé Huggies (3 x 48u)',
        descripcion: 'Triple protección con aloe vera, libres de alcohol y parabenos.',
        precio: 7200,
        precio_oferta: 5700,
        es_oferta: true,
        descuento_porcentaje: 21,
        imagen_url: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=600&auto=format&fit=crop&q=80',
        categoria: 'Bebés',
      },
      {
        id: 'p-gb-g2-3',
        comercio_id: 'ms-gold-02',
        nombre: 'Crema Hidratante Facial y Corporal Nivea Soft (200 ml)',
        descripcion: 'Con aceite de jojoba y vitamina E, textura ligera de rápida absorción.',
        precio: 6500,
        precio_oferta: 5100,
        es_oferta: true,
        descuento_porcentaje: 21,
        imagen_url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80',
        categoria: 'Cuidado Personal',
      },
      {
        id: 'p-gb-g2-4',
        comercio_id: 'ms-gold-02',
        nombre: 'Cepillo Dental Eléctrico Recargable Oral-B',
        descripcion: 'Movimiento oscilatorio rotatorio para eliminar hasta 100% más placa.',
        precio: 32000,
        precio_oferta: 25900,
        es_oferta: true,
        descuento_porcentaje: 19,
        imagen_url: 'https://images.unsplash.com/photo-1559591937-e1032b49e917?w=600&auto=format&fit=crop&q=80',
        categoria: 'Cuidado Bucal',
      },
    ],
  },

  // 13. [PREMIUM 1 - Maquinista Savio] Heladería & Café Artesanal Il Duomo
  {
    id: 'ms-prem-01',
    nombre: 'Heladería & Café Artesanal Il Duomo',
    rubro: 'Cafetería',
    direccion: 'Calle Beliera 830, Maquinista Savio',
    telefono: '+54 11 4880-9988',
    whatsapp: '+5491148809988',
    esta_abierto: true,
    latitud: -34.4340,
    longitud: -58.7825,
    descripcion: 'Helados artesanales 100% cremosos elaborados con crema de leche fresca. Cafetería de especialidad y tortas.',
    horario: 'Lunes a Domingos de 12:00 a 00:30',
    tiene_catalogo: true,
    nivel: 'premium',
    nivel_solicitado: 'premium',
    fecha_inicio_nivel: '2026-09-04T14:00:00.000Z',
    fecha_vencimiento_nivel: '2026-10-04T14:00:00.000Z',
    tipo_atencion: 'ambos',
    radio_entrega_metros: 3000,
    zona_envio_descripcion: 'Envíos en moto con conservadora térmica.',
    productos: [
      {
        id: 'p-ms-p1-1',
        comercio_id: 'ms-prem-01',
        nombre: 'Kilo de Helado Artesanal (hasta 4 gustos)',
        descripcion: 'Prueba nuestros sabores insignia: Dulce de leche granizado al rhum y Chocolate Il Duomo.',
        precio: 14000,
        precio_oferta: 11500,
        es_oferta: true,
        descuento_porcentaje: 18,
        imagen_url: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?w=600&auto=format&fit=crop&q=80',
        categoria: 'Helados',
      },
      {
        id: 'p-ms-p1-2',
        comercio_id: 'ms-prem-01',
        nombre: 'Promo Café Doble + 2 Medialunas con Jamón y Queso',
        descripcion: 'Café expreso tostado natural recién molido.',
        precio: 5500,
        precio_oferta: 4400,
        es_oferta: true,
        descuento_porcentaje: 20,
        imagen_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&auto=format&fit=crop&q=80',
        categoria: 'Cafetería',
      },
    ],
  },

  // 14. [PREMIUM 2 - Maquinista Savio] Parrilla & Restaurante El Quincho (HORARIO CORTADO)
  {
    id: 'ms-prem-02',
    nombre: 'Parrilla & Restaurante El Quincho',
    rubro: 'Gastronomía',
    direccion: 'Calle Carlos del García 340, Maquinista Savio',
    telefono: '+54 11 4880-6677',
    whatsapp: '+5491148806677',
    esta_abierto: true,
    tiene_horario_cortado: true,
    horario_manana: '12:00 - 15:30',
    horario_tarde: '20:00 - 00:30',
    latitud: -34.4380,
    longitud: -58.7865,
    descripcion: 'Parrilladas completas para compartir en familia, pastas caseras y postres criollos.',
    tiene_catalogo: true,
    nivel: 'premium',
    nivel_solicitado: 'premium',
    fecha_inicio_nivel: '2026-09-07T12:00:00.000Z',
    fecha_vencimiento_nivel: '2026-10-07T12:00:00.000Z',
    tipo_atencion: 'ambos',
    radio_entrega_metros: 3500,
    zona_envio_descripcion: 'Delivery caliente en fiambrera hermética.',
    productos: [
      {
        id: 'p-ms-p2-1',
        comercio_id: 'ms-prem-02',
        nombre: 'Parrillada Completa para 2 Personas + Papas Fritas',
        descripcion: 'Incluye asado, vacío, chorizo, morcilla, chinchulín y porción de fritas crocantes.',
        precio: 26000,
        precio_oferta: 21500,
        es_oferta: true,
        descuento_porcentaje: 17,
        imagen_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop&q=80',
        categoria: 'Parrilla',
      },
      {
        id: 'p-ms-p2-2',
        comercio_id: 'ms-prem-02',
        nombre: 'Ravioles Caseros de Ricota y Nuez con Salsa Fileto',
        descripcion: 'Masa casera al huevo con salsa suave de tomates frescos y albahaca.',
        precio: 9800,
        precio_oferta: 8200,
        es_oferta: true,
        descuento_porcentaje: 16,
        imagen_url: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=600&auto=format&fit=crop&q=80',
        categoria: 'Pastas Caseras',
      },
    ],
  },

  // 15. [PREMIUM 3 - Maquinista Savio] Panadería Artesanal La Nueva Unión
  {
    id: 'ms-prem-03',
    nombre: 'Panadería Artesanal La Nueva Unión',
    rubro: 'Panadería',
    direccion: 'Ruta 26 y Calle 9 de Julio, Maquinista Savio',
    telefono: '+54 11 4880-3344',
    whatsapp: '+5491148803344',
    esta_abierto: true,
    latitud: -34.4335,
    longitud: -58.7895,
    descripcion: 'Pan francés crocante, pan de salvado, tortas de cumpleaños por encargo y sándwiches de miga.',
    horario: 'Lunes a Domingos de 6:30 a 20:30',
    tiene_catalogo: true,
    nivel: 'premium',
    nivel_solicitado: 'premium',
    fecha_inicio_nivel: '2026-09-11T09:00:00.000Z',
    fecha_vencimiento_nivel: '2026-10-11T09:00:00.000Z',
    tipo_atencion: 'ambos',
    radio_entrega_metros: 2000,
    zona_envio_descripcion: 'Reparto barrial.',
    productos: [
      {
        id: 'p-ms-p3-1',
        comercio_id: 'ms-prem-03',
        nombre: 'Docena de Sándwiches de Miga Triples Jamón y Queso',
        descripcion: 'Pan de miga súper blanco y esponjoso con manteca y fiambre seleccionado.',
        precio: 16000,
        precio_oferta: 13200,
        es_oferta: true,
        descuento_porcentaje: 17,
        imagen_url: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=600&auto=format&fit=crop&q=80',
        categoria: 'Sándwiches de Miga',
      },
      {
        id: 'p-ms-p3-2',
        comercio_id: 'ms-prem-03',
        nombre: 'Pan Casero Redondo Horneado a la Leña (1 kg)',
        descripcion: 'Corteza dorada y miga compacta tradicional.',
        precio: 3500,
        precio_oferta: 2800,
        es_oferta: true,
        descuento_porcentaje: 20,
        imagen_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
        categoria: 'Panes',
      },
    ],
  },

  // 16. [PREMIUM 4 - Maquinista Savio] Bazar & Regalería Los Ángeles (EN VACACIONES)
  {
    id: 'ms-prem-04',
    nombre: 'Bazar & Regalería Los Ángeles',
    rubro: 'Librería',
    direccion: 'Calle San Juan Bosco 520, Maquinista Savio',
    telefono: '+54 11 4880-5566',
    whatsapp: '+5491148805566',
    esta_abierto: false,
    en_vacaciones: true,
    vacaciones_desde: '2026-09-20',
    vacaciones_hasta: '2026-09-30',
    mensaje_vacaciones: 'Receso por vacaciones de primavera. ¡Los esperamos a todos el 1 de octubre con nuevos ingresos!',
    latitud: -34.4392,
    longitud: -58.7840,
    descripcion: 'Artículos para el hogar, vajilla, termos de acero inoxidable, regalería y juguetes para niños.',
    horario: 'Lunes a Sábados de 9:00 a 19:30',
    tiene_catalogo: true,
    nivel: 'premium',
    nivel_solicitado: 'premium',
    fecha_inicio_nivel: '2026-09-01T10:00:00.000Z',
    fecha_vencimiento_nivel: '2026-10-01T10:00:00.000Z',
    tipo_atencion: 'local_fisico',
    productos: [
      {
        id: 'p-ms-p4-1',
        comercio_id: 'ms-prem-04',
        nombre: 'Termo de Acero Inoxidable Doble Capa 1 Litro',
        descripcion: 'Mantiene agua caliente por 24 horas, pico cebador matero.',
        precio: 24000,
        precio_oferta: 19500,
        es_oferta: true,
        descuento_porcentaje: 18,
        imagen_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?w=600&auto=format&fit=crop&q=80',
        categoria: 'Bazar y Mate',
      },
    ],
  },

  // 17. [STANDAR 1 - Maquinista Savio] Verdulería Don Vicente (HORARIO CORTADO)
  {
    id: 'ms-std-01',
    nombre: 'Verdulería Don Vicente',
    rubro: 'Verdulería',
    direccion: 'Calle El Ruiseñor 415, Maquinista Savio',
    telefono: '+54 11 4880-7799',
    whatsapp: '+5491148807799',
    esta_abierto: true,
    tiene_horario_cortado: true,
    horario_manana: '08:00 - 13:00',
    horario_tarde: '17:00 - 20:30',
    latitud: -34.4370,
    longitud: -58.7910,
    descripcion: 'Verdulería familiar con las mejores papas negras, cebollas y verduras de hoja recién cortadas.',
    tiene_catalogo: true,
    nivel: 'standar',
    nivel_solicitado: 'standar',
    tipo_atencion: 'local_fisico',
    productos: [
      {
        id: 'p-ms-s1-1',
        comercio_id: 'ms-std-01',
        nombre: 'Bolsa de Papas Negras Seleccionadas (5 kg)',
        descripcion: 'Ideales para puré, tortilla o papas fritas crocantes.',
        precio: 4500,
        es_oferta: false,
        categoria: 'Verduras',
      },
    ],
  },

  // 18. [STANDAR 2 - Maquinista Savio] Ferretería Savio Centro
  {
    id: 'ms-std-02',
    nombre: 'Ferretería Savio Centro',
    rubro: 'Ferretería',
    direccion: 'Calle Formosa 640, Maquinista Savio',
    telefono: '+54 11 4880-8811',
    whatsapp: '+5491148808811',
    esta_abierto: true,
    latitud: -34.4358,
    longitud: -58.7830,
    descripcion: 'Pinturería, electricidad, cerraduras, caños termofusión y asesoramiento técnico a vecinos.',
    horario: 'Lunes a Sábados de 8:00 a 19:00',
    tiene_catalogo: true,
    nivel: 'standar',
    nivel_solicitado: 'standar',
    tipo_atencion: 'local_fisico',
    productos: [
      {
        id: 'p-ms-s2-1',
        comercio_id: 'ms-std-02',
        nombre: 'Lámpara LED Luz Fría 12W Pack x 3',
        descripcion: 'Bajo consumo energético de alta luminosidad rosca común E27.',
        precio: 5200,
        es_oferta: false,
        categoria: 'Electricidad',
      },
    ],
  },

  // 19. [STANDAR 3 - Maquinista Savio] Dietética & Almacén Natural BioSavio
  {
    id: 'ms-std-03',
    nombre: 'Dietética & Almacén Natural BioSavio',
    rubro: 'Almacén',
    direccion: 'Calle Chaco 210, Maquinista Savio',
    telefono: '+54 11 4880-3300',
    whatsapp: '+5491148803300',
    esta_abierto: true,
    latitud: -34.4385,
    longitud: -58.7890,
    descripcion: 'Harinas integrales, semillas, frutos secos, productos sin TACC y suplementos nutricionales.',
    horario: 'Lunes a Sábados de 9:00 a 13:00 y de 16:30 a 20:00',
    tiene_catalogo: true,
    nivel: 'standar',
    nivel_solicitado: 'standar',
    tipo_atencion: 'local_fisico',
    productos: [
      {
        id: 'p-ms-s3-1',
        comercio_id: 'ms-std-03',
        nombre: 'Mix de Frutos Secos Clásico (500 g)',
        descripcion: 'Nueces, almendras, castañas de cajú y pasas de uva rubias.',
        precio: 7800,
        es_oferta: false,
        categoria: 'Frutos Secos',
      },
    ],
  },

  // 20. [STANDAR 4 - Maquinista Savio] Kiosco & Librería San Cayetano
  {
    id: 'ms-std-04',
    nombre: 'Kiosco & Librería San Cayetano',
    rubro: 'Kiosco',
    direccion: 'Calle Mocoretá 1050, Maquinista Savio',
    telefono: '+54 11 4880-9922',
    whatsapp: '+5491148809922',
    esta_abierto: true,
    latitud: -34.4402,
    longitud: -58.7860,
    descripcion: 'Kiosco escolar, golosinas, fotocopias, impresiones y carga virtual.',
    horario: 'Lunes a Viernes de 7:30 a 19:30 | Sábados de 9:00 a 13:30',
    tiene_catalogo: true,
    nivel: 'standar',
    nivel_solicitado: 'standar',
    tipo_atencion: 'local_fisico',
    productos: [
      {
        id: 'p-ms-s4-1',
        comercio_id: 'ms-std-04',
        nombre: 'Gaseosa Coca-Cola Original 500 ml',
        descripcion: 'Bien fría de heladera.',
        precio: 2000,
        es_oferta: false,
        categoria: 'Bebidas',
      },
    ],
  },
];
